name: fitness_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  firebase_storage: 12.4.10
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  url_launcher: ^6.2.0
  firebase_auth: ^5.0.0
  video_player: ^2.8.1 
  shared_preferences: ^2.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  cloud_firestore: ^5.6.12
  
  google_fonts: ^8.0.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/welcome_1.jpg     
    - assets/welcome_2.mp4     
    - assets/welcome_3.mp4
    - assets/supplements/amino/1.jpg
    - assets/supplements/amino/2.jpg
    - assets/supplements/amino/3.jpg
    - assets/supplements/amino/4.jpg
    - assets/supplements/amino/5.jpg 
    - assets/supplements/amino/6.jpg
    - assets/supplements/amino/7.jpg
    - assets/supplements/amino/8.jpg
    - assets/supplements/amino/9.jpg
    - assets/supplements/amino/10.jpg
    - assets/supplements/amino/11.jpg
    - assets/supplements/PRO/1.jpg   
    - assets/supplements/PRO/2.jpg
    - assets/supplements/PRO/3.jpg
    - assets/supplements/PRO/4.jpg
    - assets/supplements/PRO/5.jpg
    - assets/supplements/PRO/6.jpg
    - assets/supplements/PRO/7.jpg
    - assets/supplements/PRO/8.jpg
    - assets/supplements/PRO/9.jpg
    - assets/supplements/PRO/10.jpg
    - assets/supplements/PRO/11.jpg
    - assets/supplements/PRO/12.jpg
    - assets/supplements/PRO/13.jpg
    - assets/supplements/PRO/14.jpg
    - assets/supplements/creatine/1.jpg
    - assets/supplements/creatine/2.jpg
    - assets/supplements/creatine/3.jpg
    - assets/supplements/creatine/4.jpg
    - assets/supplements/creatine/5.jpg
    - assets/supplements/creatine/6.jpg
    - assets/supplements/creatine/7.jpg
    - assets/supplements/creatine/8.jpg
    - assets/supplements/creatine/9.jpg
    - assets/supplements/creatine/10.jpg
    - assets/supplements/creatine/11.jpg
    - assets/supplements/creatine/12.jpg
    - assets/supplements/creatine/13.jpg
    - assets/supplements/creatine/14.jpg
    - assets/supplements/snacks/1.jpg
    - assets/supplements/snacks/2.jpg
    - assets/supplements/snacks/3.jpg
    - assets/supplements/snacks/4.jpg
    - assets/supplements/snacks/5.jpg
    - assets/supplements/snacks/6.jpg
    - assets/supplements/snacks/7.jpg
    - assets/supplements/snacks/8.jpg
    - assets/supplements/snacks/9.jpg
    - assets/supplements/snacks/10.jpg
    - assets/supplements/snacks/11.jpg
    - assets/supplements/snacks/12.jpg
    - assets/supplements/snacks/13.jpg
    - assets/supplements/snacks/14.jpg
    - assets/supplements/snacks/15.jpg
    - assets/supplements/snacks/16.jpg
    - assets/supplements/snacks/17.jpg
    - assets/supplements/snacks/18.jpg
    - assets/supplements/snacks/19.jpg
    - assets/supplements/snacks/20.jpg
    - assets/supplements/snacks/21.jpg
    - assets/supplements/snacks/22.jpg
    - assets/supplements/snacks/23.jpg
    - assets/supplements/fatburn/1.jpg
    - assets/supplements/fatburn/2.jpg
    - assets/supplements/fatburn/3.jpg
    - assets/supplements/fatburn/4.jpg
    - assets/supplements/fatburn/5.jpg
    - assets/supplements/fatburn/6.jpg
    - assets/supplements/fatburn/7.jpg
    - assets/supplements/fatburn/8.jpg
    - assets/supplements/fatburn/9.jpg
    - assets/supplements/fatburn/10.jpg
    - assets/supplements/fatburn/11.jpg
    - assets/supplements/fatburn/12.jpg
    - assets/supplements/health/1.jpg
    - assets/supplements/health/2.jpg
    - assets/supplements/health/3.jpg
    - assets/supplements/health/4.jpg
    - assets/supplements/health/5.jpg
    - assets/supplements/health/6.jpg
    - assets/supplements/health/7.jpg
    - assets/supplements/health/8.jpg
    - assets/supplements/health/9.jpg
    - assets/supplements/health/10.jpg
    - assets/supplements/health/11.jpg
    - assets/supplements/health/12.jpg
    - assets/supplements/MASS/1.jpg
    - assets/supplements/MASS/2.jpg
    - assets/supplements/MASS/3.jpg
    - assets/supplements/MASS/4.jpg
    - assets/supplements/MASS/5.jpg
    - assets/supplements/MASS/6.jpg
    - assets/supplements/MASS/7.jpg
    - assets/supplements/MASS/8.jpg
    - assets/supplements/MASS/9.jpg
    - assets/supplements/MASS/10.jpg
    - assets/supplements/MASS/11.jpg
    - assets/supplements/MASS/12.jpg
    - assets/supplements/MASS/13.jpg
    - assets/supplements/MASS/14.jpg
    - assets/supplements/pre/1.jpg
    - assets/supplements/pre/2.jpg
    - assets/supplements/pre/3.jpg
    - assets/supplements/pre/4.jpg
    - assets/supplements/pre/5.jpg
    - assets/supplements/pre/6.jpg
    - assets/supplements/pre/7.jpg
    - assets/supplements/pre/8.jpg
    - assets/supplements/pre/9.jpg
    - assets/supplements/pre/10.jpg
    - assets/supplements/pre/11.jpg
    - assets/supplements/pre/12.jpg
    - assets/supplements/pre/13.jpg
    - assets/supplements/pre/14.jpg
    - assets/discount/1.jpg
    - assets/discount/2.jpg
    - assets/discount/3.jpg
    - assets/discount/4.jpg
    - assets/discount/5.jpg
    - assets/discount/6.jpg
    - assets/discount/7.jpg
    - assets/Mbeginner/chest/chest-stretch.mp4
    - assets/Mbeginner/chest/chest-press.mp4
    - assets/Mbeginner/chest/bench-press.mp4
    - assets/Mbeginner/chest/push-up.mp4
    - assets/Mbeginner/back/straight-seated-row.mp4
    - assets/Mbeginner/back/wheel-rollout.mp4
    - assets/Mbeginner/back/wide-pulldown.mp4
    - assets/Mbeginner/back/shrug.mp4
    - assets/Mbeginner/legs/seated-leg-curl.mp4
    - assets/Mbeginner/legs/leg-extension.mp4
    - assets/Mbeginner/legs/seated-calf.mp4
    - assets/Mbeginner/shoulders/lying-around-theworld.mp4
    - assets/Mbeginner/shoulders/shoulder-press.mp4
    - assets/Mbeginner/shoulders/lateral-shoulder.mp4
    - assets/Mbeginner/arms/alt-biceps.mp4
    - assets/Mbeginner/arms/curl-biceps.mp4
    - assets/Mbeginner/arms/triceps-pushdown.mp4
    - assets/Mbeginner/arms/seated-bench.mp4
    - assets/Mbeginner/core/lever-back.mp4
    - assets/Mbeginner/core/lever-seated.mp4
    - assets/Mbeginner/core/yoga-cobra.mp4  
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf  
      - asset: assets/fonts/Poppins-Bold.ttf      
      - asset: assets/fonts/Poppins-ExtraBold.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
